src/ui/EduPlatform.Web/Pages/Basket/Index.cshtml.cs
#region
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using EduPlatform.Web.PageModels;
using EduPlatform.Web.Pages.Basket.Dto;
using EduPlatform.Web.Pages.Basket.ViewModel;
using EduPlatform.Web.Services;

#endregion

namespace EduPlatform.Web.Pages.Basket;

[Authorize]
public class IndexModel(CatalogService catalogService, BasketService basketService) : BasePageModel
{
    public BasketPageViewModel Basket { get; set; } = new();


    public async Task<IActionResult> OnGet()
    {
        var basketAsResult = await basketService.GetBasketPageViewModelAsync();

        if (basketAsResult.IsFail)
            return ErrorPage(basketAsResult, "Index");
        Basket = basketAsResult.Data!;

        return Page();
    }


    public async Task<IActionResult> OnGetAddBasketAsync(Guid courseId)
    {
        var course = await catalogService.GetCourse(courseId);


        var createOrUpdateBasket = new AddBasketRequest(course.Data!.Id, course.Data.Name,
            course.Data.Price, course.Data.ImageUrl);


        var result = await basketService.CreateOrUpdateBasketAsync(createOrUpdateBasket);

        return result.IsFail ? ErrorPage(result, "Index") : SuccessPage("course added to basket", "Index");
    }

    public async Task<IActionResult> OnGetDeleteAsync(Guid courseId)
    {
        var result = await basketService.DeleteBasketAsync(courseId);

        return result.IsFail ? ErrorPage(result, "Index") : SuccessPage("course deleted from basket", "Index");
    }

    public async Task<IActionResult> OnPostApplyDiscountAsync(string couponCode)
    {
        var response = await basketService.ApplyDiscountAsync(couponCode);

        return response.IsFail ? ErrorPage(response, "Index") : SuccessPage("discount coupon applied", "Index");
    }

    public async Task<IActionResult> OnGetRemoveDiscountAsync()
    {
        var response = await basketService.RemoveDiscountAsync();

        return response.IsFail ? ErrorPage(response, "Index") : SuccessPage("discount coupon removed", "Index");
    }
}

src/ui/EduPlatform.Web/Pages/Courses/Detail.cshtml.cs
#region

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using EduPlatform.Web.PageModels;
using EduPlatform.Web.Services;
using EduPlatform.Web.ViewModel;

#endregion

namespace EduPlatform.Web.Pages.Courses;

[AllowAnonymous]
public class DetailModel(CatalogService catalogService) : BasePageModel
{
    public CourseViewModel? Course { get; set; }

    public async Task<IActionResult> OnGet(Guid id)
    {
        var courseAsResult = await catalogService.GetCourse(id);

        if (courseAsResult.IsFail) return ErrorPage(courseAsResult);

        Course = courseAsResult.Data!;
        return Page();
    }
}

src/ui/EduPlatform.Web/Pages/Instructor/Courses.cshtml.cs
#region

using EduPlatform.Web.Services;
using EduPlatform.Web.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


#endregion

public class CoursesModel(CatalogService catalogService) : PageModel
{
    public List<CourseViewModel> CourseViewModels { get; set; } = null!;

    public async Task OnGetAsync()
    {
        var result = await catalogService.GetCoursesByUserId();

        if (result.IsFail)
        {
            //TODO : redirect error page
        }

        CourseViewModels = result.Data!;
    }


    public async Task<IActionResult> OnGetDeleteAsync(Guid id)
    {
        var result = await catalogService.DeleteAsync(id);
        if (result.IsFail)
        {
            //TODO : redirect error page
        }

        return RedirectToPage();
    }
}

src/ui/EduPlatform.Web/Pages/Courses/Detail.cshtml
@page "{id:guid}"
@model DetailModel
@{
}
<div class="container mt-5">

    <div class="row">


        <div class="col-md-6">
            <div class="card shadow-lg border-0">


                <course-picture class="card-img-top img-fluid" alt="Kurs Resmi" src="@Model.Course.ImageUrl"></course-picture>
                <div class="card-body">
                    <h2 class="mb-4">@Model.Course.Name</h2>
                    <h5 class="card-title">Kurs Açıklaması</h5>
                    <p>@Model.Course.Description</p>
                </div>
            </div>
        </div>


        <div class="col-md-6">
            <div class="card shadow-lg border-0">
                <div class="card-body">

                    <h5 class="card-title">Kategori</h5>
                    <p class="card-text">@Model.Course.CategoryName</p>
                    <hr>


                    <h5 class="card-title">Fiyat</h5>
                    <p class="card-text">
                        <strong>@Model.Course.Price.ToString("C")</strong>
                    </p>
                    <hr>


                    <h5 class="card-title">Detaylar</h5>
                    <p class="card-text">
                        <small class="text-muted">Eğitmen: <strong>@Model.Course.EducatorFullName</strong></small>
                    </p>
                    <p class="card-text">
                        <small class="text-muted">Oluşturulma Tarihi: <strong>@Model.Course.Created</strong></small>
                    </p>
                    <p class="card-text">
                        <small class="text-muted">Puan: <strong>@Model.Course.Rating</strong> | Süre: <strong>@Model.Course.Duration</strong> saat</small>
                    </p>
                </div>
                <div class="card-footer bg-light text-center">
                    <a asp-page="/basket/index" asp-page-handler="AddBasket" asp-route-courseId="@Model.Course.Id" class="btn btn-primary">Add To Basket</a>
                </div>
            </div>
        </div>


    </div>


</div>